-- Consolidated PL/SQL HTM Compilation Script
-- Generated by AI Agent

PROMPT Dropping existing HTM types...

-- 1. Drop collection types that are 'TABLE OF some_object_type'
DROP TYPE HTM_VERTEX_LIST FORCE;
/
SHOW ERRORS TYPE HTM_VERTEX_LIST;
DROP TYPE HTM_ID_RANGE_LIST FORCE;
/
SHOW ERRORS TYPE HTM_ID_RANGE_LIST;
DROP TYPE HTM_LAYER_LIST FORCE;
/
SHOW ERRORS TYPE HTM_LAYER_LIST;
DROP TYPE HTM_NODE_LIST FORCE;
/
SHOW ERRORS TYPE HTM_NODE_LIST;

-- 2. Drop object types.
--    HTM_NODE depends on HTM_NUMBER_LIST for its attributes.
--    Therefore, HTM_NODE must be dropped before HTM_NUMBER_LIST.
DROP TYPE HTM_NODE FORCE;
/
SHOW ERRORS TYPE HTM_NODE;

--    These object types are now independent of other user-defined object types
--    (their collections having been dropped).
DROP TYPE HTM_VECTOR FORCE;
/
SHOW ERRORS TYPE HTM_VECTOR;
DROP TYPE HTM_ID_RANGE FORCE;
/
SHOW ERRORS TYPE HTM_ID_RANGE;
DROP TYPE HTM_LAYER_INFO FORCE;
/
SHOW ERRORS TYPE HTM_LAYER_INFO;

-- 3. Drop the base collection type HTM_NUMBER_LIST (TABLE OF NUMBER) last among types.
DROP TYPE HTM_NUMBER_LIST FORCE; 
/
SHOW ERRORS TYPE HTM_NUMBER_LIST;

PROMPT Proceeding with HTM type and package creation...

PROMPT Compiling SQL Types and Type Bodies...

-- From htm_types.sql: HTM_NUMBER_LIST
CREATE OR REPLACE TYPE HTM_NUMBER_LIST AS TABLE OF NUMBER;
/
SHOW ERRORS TYPE HTM_NUMBER_LIST;

-- From htm_types.sql: HTM_VECTOR (Specification)
CREATE OR REPLACE TYPE HTM_VECTOR AS OBJECT (
  x NUMBER,
  y NUMBER,
  z NUMBER,

  CONSTRUCTOR FUNCTION HTM_VECTOR(x_val NUMBER, y_val NUMBER, z_val NUMBER) RETURN SELF AS RESULT,
  CONSTRUCTOR FUNCTION HTM_VECTOR(ra NUMBER, dec NUMBER) RETURN SELF AS RESULT,

  MEMBER FUNCTION magnitude RETURN NUMBER,
  MEMBER PROCEDURE normalize,
  MEMBER FUNCTION dot_product(v HTM_VECTOR) RETURN NUMBER,
  MEMBER FUNCTION cross_product(v HTM_VECTOR) RETURN HTM_VECTOR,
  MEMBER FUNCTION to_string RETURN VARCHAR2
);
/
SHOW ERRORS TYPE HTM_VECTOR;

-- From htm_vector_body.sql: HTM_VECTOR (Full Body)
CREATE OR REPLACE TYPE BODY HTM_VECTOR AS
  CONSTRUCTOR FUNCTION HTM_VECTOR(x_val NUMBER, y_val NUMBER, z_val NUMBER) RETURN SELF AS RESULT IS
  BEGIN
    SELF.x := x_val;
    SELF.y := y_val;
    SELF.z := z_val;
    RETURN;
  END;

  CONSTRUCTOR FUNCTION HTM_VECTOR(ra NUMBER, dec NUMBER) RETURN SELF AS RESULT IS
    c_pi CONSTANT NUMBER := ACOS(-1);
    phi NUMBER;
    theta NUMBER;
  BEGIN
    phi := ra * (c_pi / 180.0);
    theta := (90.0 - dec) * (c_pi / 180.0);

    SELF.x := SIN(theta) * COS(phi);
    SELF.y := SIN(theta) * SIN(phi);
    SELF.z := COS(theta);
    RETURN;
  END;

  MEMBER FUNCTION magnitude RETURN NUMBER IS
  BEGIN
    RETURN SQRT(SELF.x*SELF.x + SELF.y*SELF.y + SELF.z*SELF.z);
  END;

  MEMBER PROCEDURE normalize IS
    mag NUMBER;
  BEGIN
    mag := SELF.magnitude();
    IF mag > 0 THEN
      SELF.x := SELF.x / mag;
      SELF.y := SELF.y / mag;
      SELF.z := SELF.z / mag;
    END IF;
    -- Decide on error handling if mag is 0. For now, it leaves the vector as is.
  END;

  MEMBER FUNCTION dot_product(v HTM_VECTOR) RETURN NUMBER IS
  BEGIN
    RETURN SELF.x*v.x + SELF.y*v.y + SELF.z*v.z;
  END;

  MEMBER FUNCTION cross_product(v HTM_VECTOR) RETURN HTM_VECTOR IS
    new_x NUMBER;
    new_y NUMBER;
    new_z NUMBER;
  BEGIN
    new_x := SELF.y*v.z - SELF.z*v.y;
    new_y := SELF.z*v.x - SELF.x*v.z;
    new_z := SELF.x*v.y - SELF.y*v.x;
    RETURN HTM_VECTOR(new_x, new_y, new_z);
  END;

  MEMBER FUNCTION to_string RETURN VARCHAR2 IS
  BEGIN
    RETURN '(' || TO_CHAR(SELF.x) || ', ' || TO_CHAR(SELF.y) || ', ' || TO_CHAR(SELF.z) || ')';
  END;
END;
/
SHOW ERRORS TYPE BODY HTM_VECTOR;

-- From htm_types.sql: HTM_VERTEX_LIST
CREATE OR REPLACE TYPE HTM_VERTEX_LIST AS TABLE OF HTM_VECTOR;
/
SHOW ERRORS TYPE HTM_VERTEX_LIST;

-- From htm_types.sql: HTM_ID_RANGE (Specification)
CREATE OR REPLACE TYPE HTM_ID_RANGE AS OBJECT (
  low_id NUMBER,
  high_id NUMBER,

  CONSTRUCTOR FUNCTION HTM_ID_RANGE(l_id NUMBER, h_id NUMBER) RETURN SELF AS RESULT
);
/
SHOW ERRORS TYPE HTM_ID_RANGE;

-- From htm_types.sql: HTM_ID_RANGE (Body)
CREATE OR REPLACE TYPE BODY HTM_ID_RANGE AS
  CONSTRUCTOR FUNCTION HTM_ID_RANGE(l_id NUMBER, h_id NUMBER) RETURN SELF AS RESULT IS
  BEGIN
    SELF.low_id := l_id;
    SELF.high_id := h_id;
    RETURN;
  END;
END;
/
SHOW ERRORS TYPE BODY HTM_ID_RANGE;

-- From htm_types.sql: HTM_ID_RANGE_LIST
CREATE OR REPLACE TYPE HTM_ID_RANGE_LIST AS TABLE OF HTM_ID_RANGE;
/
SHOW ERRORS TYPE HTM_ID_RANGE_LIST;

-- From htm_types.sql: HTM_NODE (Specification)
CREATE OR REPLACE TYPE HTM_NODE AS OBJECT (
  node_id NUMBER,
  parent_id NUMBER,
  level_num NUMBER,
  is_leaf NUMBER, -- 0 or 1
  children_ids HTM_NUMBER_LIST,
  v_ids HTM_NUMBER_LIST,
  w_ids HTM_NUMBER_LIST,

  CONSTRUCTOR FUNCTION HTM_NODE(
    p_node_id NUMBER,
    p_parent_id NUMBER,
    p_level_num NUMBER,
    p_is_leaf NUMBER,
    p_children_ids HTM_NUMBER_LIST,
    p_v_ids HTM_NUMBER_LIST,
    p_w_ids HTM_NUMBER_LIST DEFAULT NULL
  ) RETURN SELF AS RESULT
);
/
SHOW ERRORS TYPE HTM_NODE;

-- From htm_types.sql: HTM_NODE (Body)
CREATE OR REPLACE TYPE BODY HTM_NODE AS
  CONSTRUCTOR FUNCTION HTM_NODE(
    p_node_id NUMBER,
    p_parent_id NUMBER,
    p_level_num NUMBER,
    p_is_leaf NUMBER,
    p_children_ids HTM_NUMBER_LIST,
    p_v_ids HTM_NUMBER_LIST,
    p_w_ids HTM_NUMBER_LIST DEFAULT NULL
  ) RETURN SELF AS RESULT IS
  BEGIN
    SELF.node_id := p_node_id;
    SELF.parent_id := p_parent_id;
    SELF.level_num := p_level_num;
    SELF.is_leaf := p_is_leaf;
    SELF.children_ids := p_children_ids;
    SELF.v_ids := p_v_ids;
    SELF.w_ids := p_w_ids;
    RETURN;
  END;
END;
/
SHOW ERRORS TYPE BODY HTM_NODE;

-- From htm_types.sql: HTM_NODE_LIST
CREATE OR REPLACE TYPE HTM_NODE_LIST AS TABLE OF HTM_NODE;
/
SHOW ERRORS TYPE HTM_NODE_LIST;

-- From htm_types.sql: HTM_LAYER_INFO (Specification)
CREATE OR REPLACE TYPE HTM_LAYER_INFO AS OBJECT (
  level_num NUMBER,
  n_nodes NUMBER,
  n_vertices NUMBER,
  n_edges NUMBER,
  first_node_id NUMBER,
  first_vertex_id NUMBER,

  CONSTRUCTOR FUNCTION HTM_LAYER_INFO(
    p_level_num NUMBER,
    p_n_nodes NUMBER,
    p_n_vertices NUMBER,
    p_n_edges NUMBER,
    p_first_node_id NUMBER,
    p_first_vertex_id NUMBER
  ) RETURN SELF AS RESULT
);
/
SHOW ERRORS TYPE HTM_LAYER_INFO;

-- From htm_types.sql: HTM_LAYER_INFO (Body)
CREATE OR REPLACE TYPE BODY HTM_LAYER_INFO AS
  CONSTRUCTOR FUNCTION HTM_LAYER_INFO(
    p_level_num NUMBER,
    p_n_nodes NUMBER,
    p_n_vertices NUMBER,
    p_n_edges NUMBER,
    p_first_node_id NUMBER,
    p_first_vertex_id NUMBER
  ) RETURN SELF AS RESULT IS
  BEGIN
    SELF.level_num := p_level_num;
    SELF.n_nodes := p_n_nodes;
    SELF.n_vertices := p_n_vertices;
    SELF.n_edges := p_n_edges;
    SELF.first_node_id := p_first_node_id;
    SELF.first_vertex_id := p_first_vertex_id;
    RETURN;
  END;
END;
/
SHOW ERRORS TYPE BODY HTM_LAYER_INFO;

-- From htm_types.sql: HTM_LAYER_LIST
CREATE OR REPLACE TYPE HTM_LAYER_LIST AS TABLE OF HTM_LAYER_INFO;
/
SHOW ERRORS TYPE HTM_LAYER_LIST;

PROMPT Compiling Package Specifications...

-- From htm_geometry_utils_spec.sql
CREATE OR REPLACE PACKAGE HTM_GEOMETRY_UTILS AS

  -- PI constant
  c_pi CONSTANT NUMBER := ACOS(-1);
  -- Maximum level for HTM ID conversion (adjust as needed)
  c_max_htm_level CONSTANT INTEGER := 25; -- Corresponds to 25 pairs of bits after the initial 2 bits for N/S. Max ID would be 2 + 2*25 = 52 bits.

  -- Geometric Functions
  FUNCTION cartesian_to_ra_dec(v HTM_VECTOR) RETURN HTM_VECTOR;

  FUNCTION angle_between(v1 HTM_VECTOR, v2 HTM_VECTOR) RETURN NUMBER;

  FUNCTION is_inside_triangle(
    p HTM_VECTOR,
    v0 HTM_VECTOR,
    v1 HTM_VECTOR,
    v2 HTM_VECTOR,
    epsilon NUMBER DEFAULT 0.0000000001
  ) RETURN BOOLEAN;

  FUNCTION spherical_triangle_area(
    v0 HTM_VECTOR,
    v1 HTM_VECTOR,
    v2 HTM_VECTOR
  ) RETURN NUMBER;

  -- HTM ID Manipulation Functions
  FUNCTION id_to_name(id NUMBER) RETURN VARCHAR2;

  FUNCTION name_to_id(name VARCHAR2) RETURN NUMBER;

  FUNCTION get_triangle_vertices_from_parent(
    parent_v0 HTM_VECTOR,
    parent_v1 HTM_VECTOR,
    parent_v2 HTM_VECTOR,
    child_index NUMBER
  ) RETURN HTM_VERTEX_LIST;

END HTM_GEOMETRY_UTILS;
/
SHOW ERRORS PACKAGE HTM_GEOMETRY_UTILS;

-- From htm_index_core_spec.sql
CREATE OR REPLACE PACKAGE HTM_INDEX_CORE AS

  -- Public Procedures
  PROCEDURE initialize_htm(
    build_level NUMBER,
    query_level NUMBER
  );

  PROCEDURE get_node_vertices(
    node_id NUMBER,
    v0 OUT HTM_VECTOR,
    v1 OUT HTM_VECTOR,
    v2 OUT HTM_VECTOR
  );

  -- Public Functions
  FUNCTION get_node_info(
    node_id NUMBER
  ) RETURN HTM_NODE;

  FUNCTION id_by_point(
    p HTM_VECTOR,
    target_level NUMBER
  ) RETURN NUMBER;

  FUNCTION point_by_id(
    node_id NUMBER
  ) RETURN HTM_VECTOR;

  -- Potentially expose some global state for debugging or advanced use, if necessary
  -- For now, keep them internal to the package body.

END HTM_INDEX_CORE;
/
SHOW ERRORS PACKAGE HTM_INDEX_CORE;

-- From htm_range_utils_spec.sql
CREATE OR REPLACE PACKAGE HTM_RANGE_UTILS AS

  -- Public Procedures and Functions

  FUNCTION create_empty_range_list RETURN HTM_ID_RANGE_LIST;

  PROCEDURE add_range(
    range_list IN OUT NOCOPY HTM_ID_RANGE_LIST,
    new_low_id NUMBER,
    new_high_id NUMBER
  );

  PROCEDURE merge_ranges(
    range_list IN OUT NOCOPY HTM_ID_RANGE_LIST
  );

  FUNCTION is_id_in_ranges(
    range_list HTM_ID_RANGE_LIST,
    id_to_check NUMBER
  ) RETURN BOOLEAN;

  FUNCTION range_list_to_string(
    range_list HTM_ID_RANGE_LIST
  ) RETURN VARCHAR2;
  
  FUNCTION get_range_count(
    range_list HTM_ID_RANGE_LIST
  ) RETURN NUMBER;

END HTM_RANGE_UTILS;
/
SHOW ERRORS PACKAGE HTM_RANGE_UTILS;

-- From htm_query_interface_spec.sql
CREATE OR REPLACE PACKAGE HTM_QUERY_INTERFACE AS

  -- Public Functions
  FUNCTION circle_region_intersect(
    center_ra NUMBER,
    center_dec NUMBER,
    radius_degrees NUMBER,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST;

  FUNCTION circle_region_intersect_cartesian(
    center_vec HTM_VECTOR,
    radius_degrees NUMBER,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST;

  FUNCTION convex_hull_intersect(
    vertices_ra_dec HTM_VERTEX_LIST, -- List of RA/Dec points
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST;

  FUNCTION convex_hull_intersect_cartesian(
    vertices_cartesian HTM_VERTEX_LIST, -- List of Cartesian vectors
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST;

END HTM_QUERY_INTERFACE;
/
SHOW ERRORS PACKAGE HTM_QUERY_INTERFACE;

-- From htm_sql_api_spec.sql
CREATE OR REPLACE PACKAGE HTM_SQL_API AS

  -- Initialization Procedure
  PROCEDURE initialize_htm_system(
    p_build_level NUMBER,
    p_query_level NUMBER
  );

  -- Lookup Functions
  FUNCTION lookup_htm_id(
    p_ra NUMBER,
    p_dec NUMBER,
    p_target_level NUMBER
  ) RETURN NUMBER;

  FUNCTION get_htm_point_radec(
    p_htm_id NUMBER
  ) RETURN VARCHAR2;

  FUNCTION get_htm_point_cartesian(
    p_htm_id NUMBER
  ) RETURN HTM_VECTOR;

  -- Intersection Query Functions (Table Functions)
  FUNCTION htm_circle_intersect(
    p_ra NUMBER,
    p_dec NUMBER,
    p_radius_degrees NUMBER,
    p_query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST PIPELINED;

  FUNCTION htm_polygon_intersect(
    p_vertices_ra_dec_string VARCHAR2,
    p_query_level NUMBER,
    p_delimiter CHAR DEFAULT ';'
  ) RETURN HTM_ID_RANGE_LIST PIPELINED;

END HTM_SQL_API;
/
SHOW ERRORS PACKAGE HTM_SQL_API;

PROMPT Compiling Package Bodies...

-- From htm_geometry_utils_body.sql
CREATE OR REPLACE PACKAGE BODY HTM_GEOMETRY_UTILS AS

  -- Geometric Functions
  FUNCTION cartesian_to_ra_dec(v HTM_VECTOR) RETURN HTM_VECTOR AS
    rad_to_deg CONSTANT NUMBER := 180.0 / c_pi;
    ra NUMBER;
    dec NUMBER;
    len NUMBER;
  BEGIN
    IF v.x IS NULL OR v.y IS NULL OR v.z IS NULL THEN
      RETURN HTM_VECTOR(NULL, NULL, NULL); -- Or raise an error
    END IF;

    len := v.magnitude();
    IF len = 0 THEN
      -- Or handle as an error, e.g., point at the origin has undefined RA/Dec
      RETURN HTM_VECTOR(0, 0, 0); 
    END IF;

    -- Normalize the vector for RA/Dec calculation if not already unit
    -- This function might receive non-unit vectors if used generally
    DECLARE
      unit_v HTM_VECTOR := HTM_VECTOR(v.x/len, v.y/len, v.z/len);
    BEGIN
      dec := ASIN(unit_v.z); -- Dec in radians
      
      IF ABS(unit_v.z) > 0.999999999999 THEN -- Close to poles
        ra := 0.0; -- RA is undefined at poles, conventionally set to 0
      ELSE
        ra := ATAN2(unit_v.y, unit_v.x); -- RA in radians, range (-PI, PI]
      END IF;

      -- Convert to degrees
      ra := ra * rad_to_deg;
      dec := dec * rad_to_deg;

      -- Adjust RA to be in [0, 360)
      IF ra < 0 THEN
        ra := ra + 360.0;
      END IF;
      
      RETURN HTM_VECTOR(ra, dec, len); -- Store RA in x, Dec in y, radius in z
    END;
  END cartesian_to_ra_dec;

  FUNCTION angle_between(v1 HTM_VECTOR, v2 HTM_VECTOR) RETURN NUMBER AS
    dot_prod NUMBER;
    angle_rad NUMBER;
  BEGIN
    -- Assuming v1 and v2 are unit vectors as per the note.
    -- If not, they should be normalized first:
    -- v1.normalize();
    -- v2.normalize();
    dot_prod := v1.dot_product(v2);

    -- Clamp dot_prod to [-1, 1] to avoid domain errors with ACOS
    IF dot_prod > 1.0 THEN
      dot_prod := 1.0;
    ELSIF dot_prod < -1.0 THEN
      dot_prod := -1.0;
    END IF;

    angle_rad := ACOS(dot_prod);
    RETURN angle_rad * (180.0 / c_pi); -- Convert to degrees
  END angle_between;

  FUNCTION is_inside_triangle(
    p HTM_VECTOR,
    v0 HTM_VECTOR,
    v1 HTM_VECTOR,
    v2 HTM_VECTOR,
    epsilon NUMBER DEFAULT 0.0000000001
  ) RETURN BOOLEAN AS
    -- Assuming p, v0, v1, v2 are unit vectors.
    -- The vertices v0, v1, v2 should be in counter-clockwise order.
    c0 HTM_VECTOR;
    c1 HTM_VECTOR;
    c2 HTM_VECTOR;
  BEGIN
    c0 := v0.cross_product(v1);
    c1 := v1.cross_product(v2);
    c2 := v2.cross_product(v0);

    RETURN (c0.dot_product(p) >= -epsilon) AND
           (c1.dot_product(p) >= -epsilon) AND
           (c2.dot_product(p) >= -epsilon);
  END is_inside_triangle;

  FUNCTION spherical_triangle_area(
    v0 HTM_VECTOR,
    v1 HTM_VECTOR,
    v2 HTM_VECTOR
  ) RETURN NUMBER AS
    -- Assumes v0, v1, v2 are unit vectors
    a_rad NUMBER;
    b_rad NUMBER;
    c_rad NUMBER;
    s NUMBER;
    tan_E_4_sq NUMBER;
    deg_to_rad CONSTANT NUMBER := c_pi / 180.0;
  BEGIN
    -- Get side lengths (angles between vertices) in radians
    a_rad := angle_between(v1, v2) * deg_to_rad;
    b_rad := angle_between(v0, v2) * deg_to_rad;
    c_rad := angle_between(v0, v1) * deg_to_rad;

    s := (a_rad + b_rad + c_rad) / 2.0;

    -- L'Huilier's Theorem for spherical excess E
    -- tan(E/4)^2 = tan(s/2) * tan((s-a)/2) * tan((s-b)/2) * tan((s-c)/2)
    -- Ensure arguments to TAN are not causing issues (e.g. s/2 = PI/2)
    -- However, for a valid spherical triangle, these should be fine.
    DECLARE
      tan_s_2 NUMBER;
      tan_s_a_2 NUMBER;
      tan_s_b_2 NUMBER;
      tan_s_c_2 NUMBER;
    BEGIN
      tan_s_2     := TAN(s / 2.0);
      tan_s_a_2   := TAN((s - a_rad) / 2.0);
      tan_s_b_2   := TAN((s - b_rad) / 2.0);
      tan_s_c_2   := TAN((s - c_rad) / 2.0);
      
      tan_E_4_sq := tan_s_2 * tan_s_a_2 * tan_s_b_2 * tan_s_c_2;
    EXCEPTION
      WHEN OTHERS THEN -- Catch potential math errors if arguments to TAN are problematic
        -- This might happen if the triangle is degenerate (e.g., vertices are collinear)
        -- or if floating point precision issues lead to invalid TAN arguments.
        -- A robust solution might check triangle validity beforehand.
        RETURN 0; -- Area of a degenerate triangle can be considered 0.
    END;


    IF tan_E_4_sq < 0 THEN
        -- This can happen due to floating point inaccuracies for very small triangles
        -- or if the triangle inequality is not strictly met. Area should be non-negative.
        RETURN 0;
    END IF;
    
    -- Area E (spherical excess) = 4 * atan(sqrt(tan_E_4_sq))
    RETURN 4.0 * ATAN(SQRT(tan_E_4_sq)); -- Result in steradians
  END spherical_triangle_area;

  -- HTM ID Manipulation Functions
  FUNCTION id_to_name(id NUMBER) RETURN VARCHAR2 AS
    name_buf VARCHAR2(c_max_htm_level + 2); -- N/S + level digits + null terminator (PL/SQL handles strings)
    level_val INTEGER := 0;
    num_id NUMBER := id;
    current_bit NUMBER;
    mask NUMBER;
  BEGIN
    IF id < 8 THEN
      RETURN 'ID_TOO_SMALL'; -- Or raise error
    END IF;

    -- Determine N or S and starting level
    IF (num_id >= POWER(2, (2 * c_max_htm_level) + 2)) THEN
        RETURN 'ID_OUT_OF_RANGE'; -- Exceeds max representable ID for c_max_htm_level
    END IF;

    -- Find the most significant bit to determine the level
    -- The ID structure is S0S1 L0L1 L2L3 ...
    -- S0S1 = 10 (South) or 11 (North)
    -- Level 0 IDs are 8-11 (N0-N3, S0-S3 are not used this way typically)
    -- ID 8 = 1000 (binary) -> S0
    -- ID 9 = 1001 (binary) -> S1
    -- ID 10 = 1010 (binary) -> S2
    -- ID 11 = 1011 (binary) -> S3
    -- ID 12 = 1100 (binary) -> N0
    -- ID 13 = 1101 (binary) -> N1
    -- ID 14 = 1110 (binary) -> N2
    -- ID 15 = 1111 (binary) -> N3

    -- A simpler way is to check ranges based on the ID encoding for HTM C++ library
    -- The first 2 bits determine N/S and establish the base ID (8 for S, 12 for N at level 0)
    -- Each subsequent level adds 2 bits.
    
    -- Determine initial character (N/S)
    mask := POWER(2, (2 * c_max_htm_level) + 1); -- Bit for 'N' vs 'S' (second MSB of full ID range)
                                              -- e.g. if c_max_htm_level = 3, total bits = 2+2*3=8. mask for bit 7 (0-indexed)
                                              -- id = S0 S1 d1 d2 d3 d4 d5 d6
                                              -- S0S1 = 10 for S, 11 for N.
                                              -- if num_id AND (1 << ((level*2)+1)) 
    
    -- Simplified logic based on typical HTM ID structure:
    -- 8-11 are S0-S3, 12-15 are N0-N3 for level 0.
    -- This means the first 2 bits are 10 (S) or 11 (N).
    -- Let's find the highest set bit to determine overall length, then derive level.
    
    DECLARE
        temp_id NUMBER := num_id;
        bit_pos INTEGER := 0;
    BEGIN
        WHILE temp_id > 0 LOOP
            temp_id := FLOOR(temp_id / 2);
            bit_pos := bit_pos + 1;
        END LOOP;
        -- bit_pos is now the number of bits in the id.
        -- For an ID like N0 (12 = 1100), bit_pos = 4. Level = (4-2)/2 = 1. This isn't quite right.
        -- Number of characters in name = (number of bits - 2) / 2.
        -- Example: N01. ID has 3 parts: N, 0, 1. Level = 2. (N=11, 0=00, 1=01 -> 110001, 49dec)
        -- Number of bits for 110001 is 6. (6-2)/2 = 2. This is correct for level.
        level_val := (bit_pos - 2) / 2;
    END;


    IF BITAND(num_id, POWER(2, (level_val * 2) + 1)) != 0 THEN -- Check the N/S bit (second MSB of the ID itself)
      name_buf := 'N';
    ELSE
      name_buf := 'S';
    END IF;
    
    -- Remove the N/S prefix bits from num_id for easier digit processing
    -- num_id := BITAND(num_id, POWER(2, level_val * 2) -1 ); -- this is wrong.
    -- The ID already contains the N/S part implicitly in its value.
    -- We need to extract pairs of bits from highest level to lowest.

    FOR i IN REVERSE 0 .. level_val - 1 LOOP
      current_bit := FLOOR(num_id / POWER(2, i * 2));
      name_buf := name_buf || TO_CHAR(BITAND(current_bit, 3));
    END LOOP;
    
    RETURN name_buf;

  END id_to_name;

  FUNCTION name_to_id(name VARCHAR2) RETURN NUMBER AS
    id_val NUMBER := 0;
    level_val INTEGER;
    ch CHAR(1);
    digit INTEGER;
  BEGIN
    IF name IS NULL OR LENGTH(name) < 2 THEN
      RETURN NULL; -- Or raise error "INVALID_NAME_FORMAT"
    END IF;

    level_val := LENGTH(name) - 1;
    IF level_val > c_max_htm_level THEN
        RETURN NULL; -- Or raise error "NAME_TOO_LONG"
    END IF;

    ch := SUBSTR(name, 1, 1);

    IF ch = 'N' THEN
      id_val := 3; -- Binary 11
    ELSIF ch = 'S' THEN
      id_val := 2; -- Binary 10
    ELSE
      RETURN NULL; -- Or raise error "INVALID_NAME_PREFIX"
    END IF;

    FOR i IN 1 .. level_val LOOP
      ch := SUBSTR(name, i + 1, 1);
      IF ch < '0' OR ch > '3' THEN
        RETURN NULL; -- Or raise error "INVALID_NAME_DIGIT"
      END IF;
      digit := TO_NUMBER(ch);
      id_val := id_val * 4 + digit; -- Equivalent to (id_val << 2) | digit
    END LOOP;

    RETURN id_val;
  END name_to_id;

  FUNCTION get_triangle_vertices_from_parent(
    parent_v0 HTM_VECTOR,
    parent_v1 HTM_VECTOR,
    parent_v2 HTM_VECTOR,
    child_index NUMBER
  ) RETURN HTM_VERTEX_LIST AS
    w0 HTM_VECTOR;
    w1 HTM_VECTOR;
    w2 HTM_VECTOR;
    result_vertices HTM_VERTEX_LIST := HTM_VERTEX_LIST();
  BEGIN
    -- Calculate midpoints (normalized)
    w0 := HTM_VECTOR(parent_v1.x + parent_v2.x, parent_v1.y + parent_v2.y, parent_v1.z + parent_v2.z);
    w0.normalize();
    w1 := HTM_VECTOR(parent_v0.x + parent_v2.x, parent_v0.y + parent_v2.y, parent_v0.z + parent_v2.z);
    w1.normalize();
    w2 := HTM_VECTOR(parent_v0.x + parent_v1.x, parent_v0.y + parent_v1.y, parent_v0.z + parent_v1.z);
    w2.normalize();

    result_vertices.EXTEND(3);

    IF child_index = 0 THEN
      result_vertices(1) := parent_v0;
      result_vertices(2) := w2;
      result_vertices(3) := w1;
    ELSIF child_index = 1 THEN
      result_vertices(1) := parent_v1;
      result_vertices(2) := w0;
      result_vertices(3) := w2;
    ELSIF child_index = 2 THEN
      result_vertices(1) := parent_v2;
      result_vertices(2) := w1;
      result_vertices(3) := w0;
    ELSIF child_index = 3 THEN
      result_vertices(1) := w0;
      result_vertices(2) := w1;
      result_vertices(3) := w2;
    ELSE
      -- Invalid child_index, return empty or raise error
      RETURN HTM_VERTEX_LIST(); -- Or RAISE_APPLICATION_ERROR(-20001, 'Invalid child index');
    END IF;

    RETURN result_vertices;
  END get_triangle_vertices_from_parent;

END HTM_GEOMETRY_UTILS;
/
SHOW ERRORS PACKAGE BODY HTM_GEOMETRY_UTILS;

-- From htm_index_core_body.sql
CREATE OR REPLACE PACKAGE BODY HTM_INDEX_CORE AS

  -- Global Variables/State
  g_max_build_level NUMBER;
  g_max_query_level NUMBER;
  
  TYPE htm_node_assoc_array IS TABLE OF HTM_NODE INDEX BY PLS_INTEGER; -- Node_ID is the index
  g_nodes htm_node_assoc_array;
  
  g_vertices HTM_VERTEX_LIST := HTM_VERTEX_LIST();
  g_layers HTM_LAYER_LIST := HTM_LAYER_LIST();

  -- Private helper to add a vertex if it's new, returns its index
  FUNCTION add_vertex_if_new(v HTM_VECTOR, existing_vertices IN OUT NOCOPY HTM_VERTEX_LIST) RETURN PLS_INTEGER IS
    epsilon CONSTANT NUMBER := 0.0000000001; -- For comparing vectors
    idx PLS_INTEGER;
  BEGIN
    FOR i IN 1 .. existing_vertices.COUNT LOOP
      -- Check if vertex already exists (within epsilon)
      IF (ABS(existing_vertices(i).x - v.x) < epsilon AND
          ABS(existing_vertices(i).y - v.y) < epsilon AND
          ABS(existing_vertices(i).z - v.z) < epsilon)
      THEN
        RETURN i - 1; -- 0-indexed
      END IF;
    END LOOP;
    -- If not found, add it
    existing_vertices.EXTEND;
    existing_vertices(existing_vertices.LAST) := v;
    RETURN existing_vertices.LAST - 1; -- 0-indexed
  END add_vertex_if_new;

  -- Private function for creating nodes
  FUNCTION new_node_internal(
    p_node_id NUMBER,
    p_parent_id NUMBER,
    p_level_num NUMBER,
    p_is_leaf NUMBER,
    p_v_indices HTM_NUMBER_LIST -- Indices into g_vertices
  ) RETURN HTM_NODE IS
    node_children_ids HTM_NUMBER_LIST; -- Initially empty for new nodes
  BEGIN
    -- p_children_ids is empty for now, will be filled by make_new_layer
    -- Initialize node_children_ids to an empty list if HTM_NODE constructor expects a non-null collection
    node_children_ids := HTM_NUMBER_LIST(); 
    RETURN HTM_NODE(
      node_id => p_node_id,
      parent_id => p_parent_id,
      level_num => p_level_num,
      is_leaf => p_is_leaf,
      children_ids => node_children_ids, 
      v_ids => p_v_indices,
      w_ids => NULL -- w_ids (midpoint vertex indices) are not directly stored in the node this way
    );
  END new_node_internal;

  -- Private procedure to build layers
  PROCEDURE make_new_layer(current_build_level NUMBER) IS
    parent_node HTM_NODE;
    parent_node_id NUMBER;
    child_node_id NUMBER;
    child_node HTM_NODE;
    
    v_indices HTM_NUMBER_LIST;
    v0 HTM_VECTOR;
    v1 HTM_VECTOR;
    v2 HTM_VECTOR;
    
    w0_vec HTM_VECTOR;
    w1_vec HTM_VECTOR;
    w2_vec HTM_VECTOR;
    w0_idx PLS_INTEGER;
    w1_idx PLS_INTEGER;
    w2_idx PLS_INTEGER;

    child_v_indices HTM_NUMBER_LIST := HTM_NUMBER_LIST(); -- Initialize empty, then EXTEND
    num_nodes_in_layer NUMBER := 0;
    num_new_vertices NUMBER := 0; -- Track new vertices for this layer
    
    current_layer_nodes HTM_NODE_LIST := HTM_NODE_LIST();
  BEGIN
    -- Collect all nodes from the current_build_level
    parent_node_id := g_nodes.FIRST;
    WHILE parent_node_id IS NOT NULL LOOP
        IF g_nodes(parent_node_id).level_num = current_build_level THEN
            current_layer_nodes.EXTEND;
            current_layer_nodes(current_layer_nodes.LAST) := g_nodes(parent_node_id);
        END IF;
        parent_node_id := g_nodes.NEXT(parent_node_id);
    END LOOP;

    IF current_layer_nodes.COUNT = 0 THEN
      RETURN; -- No nodes at this level to process
    END IF;

    FOR i IN 1 .. current_layer_nodes.COUNT LOOP
      parent_node := current_layer_nodes(i);
      parent_node_id := parent_node.node_id;

      -- Get parent vertices from g_vertices using indices from parent_node.v_ids
      v0 := g_vertices(parent_node.v_ids(1) + 1); -- v_ids are 0-indexed
      v1 := g_vertices(parent_node.v_ids(2) + 1);
      v2 := g_vertices(parent_node.v_ids(3) + 1);

      -- Calculate midpoints
      w0_vec := HTM_VECTOR((v1.x + v2.x)/2, (v1.y + v2.y)/2, (v1.z + v2.z)/2); w0_vec.normalize();
      w1_vec := HTM_VECTOR((v0.x + v2.x)/2, (v0.y + v2.y)/2, (v0.z + v2.z)/2); w1_vec.normalize();
      w2_vec := HTM_VECTOR((v0.x + v1.x)/2, (v0.y + v1.y)/2, (v0.z + v1.z)/2); w2_vec.normalize();

      -- Add midpoints to g_vertices if they are new, get their indices
      w0_idx := add_vertex_if_new(w0_vec, g_vertices);
      w1_idx := add_vertex_if_new(w1_vec, g_vertices);
      w2_idx := add_vertex_if_new(w2_vec, g_vertices);
      
      -- Update parent node to mark it as not a leaf and store children IDs
      g_nodes(parent_node_id).is_leaf := 0;
      g_nodes(parent_node_id).children_ids.DELETE; -- Clear if any old (shouldn't be)
      g_nodes(parent_node_id).children_ids.EXTEND(4);

      -- Create 4 child nodes
      FOR child_idx IN 0 .. 3 LOOP
        child_node_id := (parent_node_id * 4) + child_idx; -- Or (parent_node_id << 2) | child_idx
        
        child_v_indices.DELETE; -- Clear before reuse or re-initialize: child_v_indices := HTM_NUMBER_LIST();
        child_v_indices.EXTEND(3);

        CASE child_idx
          WHEN 0 THEN -- v0, w2, w1
            child_v_indices(1) := parent_node.v_ids(1); child_v_indices(2) := w2_idx; child_v_indices(3) := w1_idx;
          WHEN 1 THEN -- v1, w0, w2
            child_v_indices(1) := parent_node.v_ids(2); child_v_indices(2) := w0_idx; child_v_indices(3) := w2_idx;
          WHEN 2 THEN -- v2, w1, w0
            child_v_indices(1) := parent_node.v_ids(3); child_v_indices(2) := w1_idx; child_v_indices(3) := w0_idx;
          WHEN 3 THEN -- w0, w1, w2 (central triangle)
            child_v_indices(1) := w0_idx; child_v_indices(2) := w1_idx; child_v_indices(3) := w2_idx;
        END CASE;

        child_node := new_node_internal(
          p_node_id => child_node_id,
          p_parent_id => parent_node_id,
          p_level_num => current_build_level + 1,
          p_is_leaf => 1, -- Initially leaf, may become parent later
          p_v_indices => child_v_indices
        );
        g_nodes(child_node_id) := child_node;
        g_nodes(parent_node_id).children_ids(child_idx + 1) := child_node_id;
        num_nodes_in_layer := num_nodes_in_layer + 1;
      END LOOP;
    END LOOP;
    
    -- Update g_layers for the newly created layer
    g_layers.EXTEND;
    g_layers(g_layers.LAST) := HTM_LAYER_INFO(
      p_level_num => current_build_level + 1,
      p_n_nodes => num_nodes_in_layer,
      p_n_vertices => g_vertices.COUNT, -- Total vertices up to this layer
      p_n_edges => num_nodes_in_layer * 3, -- Each node has 3 edges
      p_first_node_id => (g_layers(g_layers.LAST-1).first_node_id * 4), -- Approximate, depends on ID scheme
      p_first_vertex_id => g_layers(g_layers.LAST-1).n_vertices -- Index of first new vertex for this layer
    );

  END make_new_layer;

  -- Public Procedures
  PROCEDURE initialize_htm(build_level NUMBER, query_level NUMBER) IS
    v_indices HTM_NUMBER_LIST := HTM_NUMBER_LIST(); -- Initialize empty, then EXTEND
    node_id NUMBER;
    
    -- Initial vertices of the octahedron (0-indexed for g_vertices)
    -- X+, X-, Y+, Y-, Z+, Z-
    v_data CONSTANT HTM_VERTEX_LIST := HTM_VERTEX_LIST(
      HTM_VECTOR(1, 0, 0), HTM_VECTOR(-1, 0, 0),
      HTM_VECTOR(0, 1, 0), HTM_VECTOR(0, -1, 0),
      HTM_VECTOR(0, 0, 1), HTM_VECTOR(0, 0, -1)
    );
    
    -- Initial 8 triangles (level 0)
    -- S0-S3 (IDs 8-11), N0-N3 (IDs 12-15)
    -- Vertex indices for each of the 8 base triangles (0-indexed referring to v_data)
    -- These are chosen to match the SpatialIndex.cpp orientation.
    -- S0: (0,5,3) -> v_data indices: X+, Z-, Y-
    -- S1: (3,5,1) -> Y-, Z-, X-
    -- S2: (1,5,2) -> X-, Z-, Y+
    -- S3: (2,5,0) -> Y+, Z-, X+
    -- N0: (0,2,4) -> X+, Y+, Z+
    -- N1: (2,1,4) -> Y+, X-, Z+
    -- N2: (1,3,4) -> X-, Y-, Z+
    -- N3: (3,0,4) -> Y-, X+, Z+
    TYPE base_triangle_def IS RECORD (id NUMBER, v_idx HTM_NUMBER_LIST);
    TYPE base_triangle_list IS TABLE OF base_triangle_def;
    initial_triangles CONSTANT base_triangle_list := base_triangle_list(
        base_triangle_def(8, HTM_NUMBER_LIST(0, 5, 3)), -- S0
        base_triangle_def(9, HTM_NUMBER_LIST(3, 5, 1)), -- S1
        base_triangle_def(10, HTM_NUMBER_LIST(1, 5, 2)),-- S2
        base_triangle_def(11, HTM_NUMBER_LIST(2, 5, 0)),-- S3
        base_triangle_def(12, HTM_NUMBER_LIST(0, 2, 4)),-- N0
        base_triangle_def(13, HTM_NUMBER_LIST(2, 1, 4)),-- N1
        base_triangle_def(14, HTM_NUMBER_LIST(1, 3, 4)),-- N2
        base_triangle_def(15, HTM_NUMBER_LIST(3, 0, 4)) -- N3
    );
    
  BEGIN
    v_indices.EXTEND(3); -- For base triangles
    g_max_build_level := build_level;
    g_max_query_level := query_level;

    g_nodes.DELETE;
    g_vertices.DELETE;
    g_layers.DELETE;

    -- Add initial 6 vertices to g_vertices
    FOR i IN 1 .. v_data.COUNT LOOP
      g_vertices.EXTEND;
      g_vertices(i) := v_data(i);
    END LOOP;

    -- Create the 8 base triangles (level 0)
    FOR i IN 1 .. initial_triangles.COUNT LOOP
      node_id := initial_triangles(i).id;
      v_indices := initial_triangles(i).v_idx;
      
      g_nodes(node_id) := new_node_internal(
        p_node_id => node_id,
        p_parent_id => 0, -- Root nodes have no parent, or use a sentinel like 0 or -1
        p_level_num => 0,
        p_is_leaf => CASE WHEN build_level = 0 THEN 1 ELSE 0 END,
        p_v_indices => v_indices
      );
    END LOOP;
    
    g_layers.EXTEND;
    g_layers(1) := HTM_LAYER_INFO(
      p_level_num => 0,
      p_n_nodes => 8,
      p_n_vertices => 6,
      p_n_edges => 8 * 3,
      p_first_node_id => 8, -- Smallest ID for level 0
      p_first_vertex_id => 0 -- First vertex index
    );

    -- Iteratively build layers up to g_max_build_level
    FOR l IN 0 .. g_max_build_level - 1 LOOP
      make_new_layer(l);
    END LOOP;

  END initialize_htm;

  PROCEDURE get_node_vertices(
    node_id NUMBER,
    v0 OUT HTM_VECTOR,
    v1 OUT HTM_VECTOR,
    v2 OUT HTM_VECTOR
  ) IS
    current_node HTM_NODE;
    current_node_id NUMBER := node_id;
    parent_node_id NUMBER;
    target_level NUMBER;
    current_level NUMBER;
    child_index_path HTM_NUMBER_LIST := HTM_NUMBER_LIST(); -- Stores child indices from build_level to target_level
    
    temp_v0 HTM_VECTOR;
    temp_v1 HTM_VECTOR;
    temp_v2 HTM_VECTOR;
    child_vertices HTM_VERTEX_LIST;
  BEGIN
    IF g_nodes.EXISTS(node_id) AND g_nodes(node_id).level_num <= g_max_build_level THEN
      -- Node is pre-built
      current_node := g_nodes(node_id);
      v0 := g_vertices(current_node.v_ids(1) + 1);
      v1 := g_vertices(current_node.v_ids(2) + 1);
      v2 := g_vertices(current_node.v_ids(3) + 1);
    ELSE
      -- Node needs to be dynamically constructed
      target_level := HTM_GEOMETRY_UTILS.name_to_id(HTM_GEOMETRY_UTILS.id_to_name(node_id)); -- This is not right.
                                                                                            -- We need the level from the ID.
      -- A way to get level from ID:
      DECLARE
          name_rep VARCHAR2(100) := HTM_GEOMETRY_UTILS.id_to_name(node_id);
      BEGIN
          IF name_rep LIKE 'ID_TOO_SMALL' OR name_rep LIKE 'ID_OUT_OF_RANGE' THEN
            RAISE_APPLICATION_ERROR(-20002, 'Invalid node ID for level detection.');
          END IF;
          target_level := LENGTH(name_rep) - 1; -- 'N' or 'S' + digits for level
      END;


      IF target_level > g_max_query_level THEN
        RAISE_APPLICATION_ERROR(-20001, 'Node ID exceeds max query level.');
      END IF;

      -- Find ancestor at g_max_build_level
      current_level := target_level;
      parent_node_id := current_node_id;
      
      child_index_path.DELETE; -- Ensure it's empty

      WHILE current_level > g_max_build_level LOOP
        child_index_path(child_index_path.COUNT + 1) := MOD(parent_node_id, 4); -- Child index (0-3)
        parent_node_id := FLOOR(parent_node_id / 4);
        current_level := current_level - 1;
      END LOOP;

      -- Now parent_node_id is at g_max_build_level (or it's a root if target_level < g_max_build_level)
      IF NOT g_nodes.EXISTS(parent_node_id) THEN
         RAISE_APPLICATION_ERROR(-20003, 'Ancestor node at build level not found for ID: ' || node_id);
      END IF;
      
      current_node := g_nodes(parent_node_id);
      temp_v0 := g_vertices(current_node.v_ids(1) + 1);
      temp_v1 := g_vertices(current_node.v_ids(2) + 1);
      temp_v2 := g_vertices(current_node.v_ids(3) + 1);

      -- Iteratively apply get_triangle_vertices_from_parent
      -- Path is stored "backwards", so iterate from last to first
      FOR i IN REVERSE 1 .. child_index_path.COUNT LOOP
        child_vertices := HTM_GEOMETRY_UTILS.get_triangle_vertices_from_parent(
          temp_v0, temp_v1, temp_v2, child_index_path(i)
        );
        IF child_vertices IS NULL OR child_vertices.COUNT < 3 THEN
            RAISE_APPLICATION_ERROR(-20004, 'Failed to get child vertices dynamically for ID: ' || node_id);
        END IF;
        temp_v0 := child_vertices(1);
        temp_v1 := child_vertices(2);
        temp_v2 := child_vertices(3);
      END LOOP;
      
      v0 := temp_v0;
      v1 := temp_v1;
      v2 := temp_v2;
    END IF;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(-20005, 'Node ID not found: ' || node_id);
    WHEN OTHERS THEN
      RAISE; -- Re-raise other exceptions
  END get_node_vertices;

  -- Public Functions
  FUNCTION get_node_info(node_id NUMBER) RETURN HTM_NODE IS
    node_level NUMBER;
    node_parent_id NUMBER;
    is_leaf_node NUMBER;
    node_name VARCHAR2(100);
    children HTM_NUMBER_LIST := HTM_NUMBER_LIST();
    v_ids_placeholder HTM_NUMBER_LIST := HTM_NUMBER_LIST(); -- Placeholder, actual vertices via get_node_vertices
  BEGIN
    v_ids_placeholder.EXTEND(3); -- Initialize with 3 nulls or dummy values if needed by constructor
    v_ids_placeholder(1) := 0; v_ids_placeholder(2) := 0; v_ids_placeholder(3) := 0;

    IF g_nodes.EXISTS(node_id) THEN
      RETURN g_nodes(node_id);
    ELSE
      -- Dynamically construct node info (mostly for level, parent, and potential children)
      node_name := HTM_GEOMETRY_UTILS.id_to_name(node_id);
      IF node_name LIKE 'ID_TOO_SMALL' OR node_name LIKE 'ID_OUT_OF_RANGE' THEN
        RAISE_APPLICATION_ERROR(-20010, 'Invalid node ID for dynamic info: ' || node_id);
      END IF;
      node_level := LENGTH(node_name) - 1;

      IF node_level = 0 THEN
        node_parent_id := 0; -- Root
      ELSE
        node_parent_id := FLOOR(node_id / 4);
      END IF;
      
      is_leaf_node := CASE WHEN node_level >= g_max_query_level THEN 1 ELSE 0 END;
      -- If not leaf, children could be calculated
      IF is_leaf_node = 0 THEN
        children.EXTEND(4);
        FOR i IN 0..3 LOOP
            children(i+1) := (node_id * 4) + i;
        END LOOP;
      END IF;

      RETURN HTM_NODE(
        node_id => node_id,
        parent_id => node_parent_id,
        level_num => node_level,
        is_leaf => is_leaf_node,
        children_ids => children,
        v_ids => v_ids_placeholder, -- Not accurate here, use get_node_vertices
        w_ids => NULL
      );
    END IF;
  END get_node_info;

  FUNCTION id_by_point(p HTM_VECTOR, target_level NUMBER) RETURN NUMBER IS
    current_node_id NUMBER;
    v0 HTM_VECTOR;
    v1 HTM_VECTOR;
    v2 HTM_VECTOR;
    child_vertices HTM_VERTEX_LIST;
    found_in_child BOOLEAN;
    
    -- Start with level 0 nodes (IDs 8-15)
    level0_ids HTM_NUMBER_LIST := HTM_NUMBER_LIST(8,9,10,11,12,13,14,15);
  BEGIN
    IF target_level < 0 OR target_level > g_max_query_level THEN
      RAISE_APPLICATION_ERROR(-20020, 'Target level out of range.');
    END IF;

    -- Find which level 0 triangle contains the point
    current_node_id := -1;
    FOR i IN 1 .. level0_ids.COUNT LOOP
      get_node_vertices(level0_ids(i), v0, v1, v2);
      IF HTM_GEOMETRY_UTILS.is_inside_triangle(p, v0, v1, v2) THEN
        current_node_id := level0_ids(i);
        EXIT;
      END IF;
    END LOOP;

    IF current_node_id = -1 THEN
      RAISE_APPLICATION_ERROR(-20021, 'Point not found in any level 0 triangle. Point: ' || p.to_string());
    END IF;

    -- Iteratively descend to target_level
    FOR current_level IN 0 .. target_level - 1 LOOP
      get_node_vertices(current_node_id, v0, v1, v2); -- Get vertices of current parent
      found_in_child := FALSE;
      FOR child_idx IN 0 .. 3 LOOP
        child_vertices := HTM_GEOMETRY_UTILS.get_triangle_vertices_from_parent(v0, v1, v2, child_idx);
        IF HTM_GEOMETRY_UTILS.is_inside_triangle(p, child_vertices(1), child_vertices(2), child_vertices(3)) THEN
          current_node_id := (current_node_id * 4) + child_idx;
          found_in_child := TRUE;
          EXIT;
        END IF;
      END LOOP;
      IF NOT found_in_child THEN
         -- This can happen due to precision issues at triangle boundaries.
         -- Default to child 0 or the "closest" if a more robust method is needed.
         -- For now, if it's not in any, it implies an issue or point exactly on an edge shared by deeper children.
         -- For simplicity, we can assume it must fall in one.
         -- A more robust solution might be needed if points on edges are common and problematic.
         -- One strategy is to pick the child whose center is closest to P, or the first one that contained it if multiple do (due to epsilon).
         RAISE_APPLICATION_ERROR(-20022, 'Point ' || p.to_string() || ' not found in any child of node ' || current_node_id || ' at level ' || current_level);
      END IF;
    END LOOP;

    RETURN current_node_id;
  END id_by_point;

  FUNCTION point_by_id(node_id NUMBER) RETURN HTM_VECTOR IS
    v0 HTM_VECTOR;
    v1 HTM_VECTOR;
    v2 HTM_VECTOR;
    center_vec HTM_VECTOR;
  BEGIN
    get_node_vertices(node_id, v0, v1, v2);
    center_vec := HTM_VECTOR(v0.x + v1.x + v2.x, v0.y + v1.y + v2.y, v0.z + v1.z + v2.z);
    center_vec.normalize();
    RETURN center_vec;
  END point_by_id;

END HTM_INDEX_CORE;
/
SHOW ERRORS PACKAGE BODY HTM_INDEX_CORE;

-- From htm_range_utils_body.sql
CREATE OR REPLACE PACKAGE BODY HTM_RANGE_UTILS AS

  FUNCTION create_empty_range_list RETURN HTM_ID_RANGE_LIST IS
  BEGIN
    RETURN HTM_ID_RANGE_LIST();
  END create_empty_range_list;

  -- Private procedure to sort HTM_ID_RANGE_LIST by low_id, then high_id
  -- Using a simple bubble sort for demonstration.
  -- For large lists, more efficient sorting (e.g., merge sort, or using a global temporary table with ORDER BY) would be better.
  PROCEDURE sort_range_list(range_list IN OUT NOCOPY HTM_ID_RANGE_LIST) IS
    n PLS_INTEGER;
    temp_range HTM_ID_RANGE;
    swapped BOOLEAN;
  BEGIN
    IF range_list IS NULL OR range_list.COUNT < 2 THEN
      RETURN;
    END IF;

    n := range_list.COUNT;
    LOOP
      swapped := FALSE;
      FOR i IN 1 .. n - 1 LOOP
        IF (range_list(i).low_id > range_list(i+1).low_id) OR
           (range_list(i).low_id = range_list(i+1).low_id AND range_list(i).high_id > range_list(i+1).high_id)
        THEN
          temp_range := range_list(i);
          range_list(i) := range_list(i+1);
          range_list(i+1) := temp_range;
          swapped := TRUE;
        END IF;
      END LOOP;
      n := n - 1;
      EXIT WHEN NOT swapped;
    END LOOP;
  END sort_range_list;

  PROCEDURE merge_ranges(range_list IN OUT NOCOPY HTM_ID_RANGE_LIST) IS
    merged_list HTM_ID_RANGE_LIST;
    current_merged_range HTM_ID_RANGE;
  BEGIN
    IF range_list IS NULL OR range_list.COUNT < 2 THEN
      RETURN; -- Nothing to merge
    END IF;

    -- Sort the list first
    sort_range_list(range_list);

    merged_list := HTM_ID_RANGE_LIST();
    merged_list.EXTEND;
    merged_list(1) := range_list(1); -- Initialize with the first range

    FOR i IN 2 .. range_list.COUNT LOOP
      current_merged_range := merged_list(merged_list.LAST);
      IF range_list(i).low_id <= current_merged_range.high_id + 1 THEN
        -- Overlap or adjacent: merge
        current_merged_range.high_id := GREATEST(current_merged_range.high_id, range_list(i).high_id);
        merged_list(merged_list.LAST) := current_merged_range; -- Update the last element in merged_list
      ELSE
        -- Gap: add the new range as a separate element
        merged_list.EXTEND;
        merged_list(merged_list.LAST) := range_list(i);
      END IF;
    END LOOP;

    range_list := merged_list; -- Replace original list with merged one
  END merge_ranges;

  PROCEDURE add_range(
    range_list IN OUT NOCOPY HTM_ID_RANGE_LIST,
    new_low_id NUMBER,
    new_high_id NUMBER
  ) IS
    temp_low NUMBER := new_low_id;
    temp_high NUMBER := new_high_id;
  BEGIN
    IF temp_low IS NULL OR temp_high IS NULL THEN
        RAISE_APPLICATION_ERROR(-20101, 'New range IDs cannot be null.');
    END IF;

    IF temp_low > temp_high THEN
      -- Option 1: Raise an error
      RAISE_APPLICATION_ERROR(-20100, 'low_id cannot be greater than high_id.');
      -- Option 2: Swap them (uncomment to use)
      -- DECLARE swap_val NUMBER := temp_low;
      -- BEGIN temp_low := temp_high; temp_high := swap_val; END;
      -- Option 3: Ignore (do nothing, effectively what happens if error is not raised)
      -- RETURN; 
    END IF;
    
    IF range_list IS NULL THEN
      range_list := HTM_ID_RANGE_LIST();
    END IF;

    range_list.EXTEND;
    range_list(range_list.LAST) := HTM_ID_RANGE(temp_low, temp_high);
    
    -- Always merge after adding to maintain a minimal, sorted list
    merge_ranges(range_list);
  END add_range;

  FUNCTION is_id_in_ranges(
    range_list HTM_ID_RANGE_LIST,
    id_to_check NUMBER
  ) RETURN BOOLEAN IS
  BEGIN
    IF range_list IS NULL OR range_list.COUNT = 0 OR id_to_check IS NULL THEN
      RETURN FALSE;
    END IF;

    -- Assumes range_list is already merged and sorted (by add_range/merge_ranges)
    FOR i IN 1 .. range_list.COUNT LOOP
      IF id_to_check < range_list(i).low_id THEN
        RETURN FALSE; -- Sorted list, id is smaller than current range's low, so won't be in subsequent ranges
      END IF;
      IF id_to_check >= range_list(i).low_id AND id_to_check <= range_list(i).high_id THEN
        RETURN TRUE;
      END IF;
    END LOOP;
    RETURN FALSE;
  END is_id_in_ranges;

  FUNCTION range_list_to_string(
    range_list HTM_ID_RANGE_LIST
  ) RETURN VARCHAR2 IS
    str_repr VARCHAR2(32767) := '[';
  BEGIN
    IF range_list IS NULL OR range_list.COUNT = 0 THEN
      RETURN '[]';
    END IF;

    FOR i IN 1 .. range_list.COUNT LOOP
      IF i > 1 THEN
        str_repr := str_repr || ', ';
      END IF;
      str_repr := str_repr || '(' || TO_CHAR(range_list(i).low_id) || ',' || TO_CHAR(range_list(i).high_id) || ')';
    END LOOP;
    str_repr := str_repr || ']';
    RETURN str_repr;
  END range_list_to_string;
  
  FUNCTION get_range_count(
    range_list HTM_ID_RANGE_LIST
  ) RETURN NUMBER IS
  BEGIN
    IF range_list IS NULL THEN
      RETURN 0;
    END IF;
    RETURN range_list.COUNT;
  END get_range_count;

END HTM_RANGE_UTILS;
/
SHOW ERRORS PACKAGE BODY HTM_RANGE_UTILS;

-- From htm_query_interface_body.sql
CREATE OR REPLACE PACKAGE BODY HTM_QUERY_INTERFACE AS

  -- Constants for intersection status
  c_status_full_outside CONSTANT INTEGER := 0;
  c_status_full_inside CONSTANT INTEGER := 1;
  c_status_partial_intersect CONSTANT INTEGER := 2;
  
  c_epsilon CONSTANT NUMBER := 0.0000000001; -- For floating point comparisons in dot products

  -- Record types for query shape parameters
  TYPE type_circle_params IS RECORD (
    center_vec HTM_VECTOR,
    cos_radius NUMBER
  );

  TYPE type_hull_params IS RECORD (
    constraint_planes HTM_VERTEX_LIST -- List of normal vectors for the hull planes
  );

  -- Forward declaration of the recursive helper
  PROCEDURE intersect_node_recursive(
    node_id NUMBER,
    p_query_level NUMBER,
    p_circle_params type_circle_params,
    p_hull_params type_hull_params,
    p_is_circle_query BOOLEAN,
    current_results IN OUT NOCOPY HTM_ID_RANGE_LIST
  );

  -----------------------------------------------------------------------------
  -- Intersection Status Checkers
  -----------------------------------------------------------------------------
  FUNCTION check_triangle_circle_intersect_status(
    v0 HTM_VECTOR, v1 HTM_VECTOR, v2 HTM_VECTOR, -- Triangle vertices
    params type_circle_params
  ) RETURN INTEGER IS
    v_in_count INTEGER := 0;
    -- dot products for each vertex with circle center
    dot0 NUMBER;
    dot1 NUMBER;
    dot2 NUMBER;
  BEGIN
    dot0 := params.center_vec.dot_product(v0);
    dot1 := params.center_vec.dot_product(v1);
    dot2 := params.center_vec.dot_product(v2);

    IF dot0 >= params.cos_radius - c_epsilon THEN v_in_count := v_in_count + 1; END IF;
    IF dot1 >= params.cos_radius - c_epsilon THEN v_in_count := v_in_count + 1; END IF;
    IF dot2 >= params.cos_radius - c_epsilon THEN v_in_count := v_in_count + 1; END IF;

    IF v_in_count = 3 THEN
      RETURN c_status_full_inside;
    END IF;

    -- If all vertices are outside the circle.
    -- This is a simplification. A more robust check would involve edge intersections.
    -- For HTM, if not all in, and not all very far out, it's often treated as partial.
    IF dot0 < params.cos_radius + c_epsilon AND 
       dot1 < params.cos_radius + c_epsilon AND 
       dot2 < params.cos_radius + c_epsilon THEN
        -- All vertices are outside. Now check if circle center is inside triangle. If so, it's partial.
        IF HTM_GEOMETRY_UTILS.is_inside_triangle(params.center_vec, v0, v1, v2, c_epsilon) THEN
            RETURN c_status_partial_intersect; -- Small circle inside a larger triangle
        END IF;
        
        -- Additional check: if any triangle vertex is very close to the circle boundary, or any edge might cross.
        -- For simplicity, we'll rely on recursion for partial cases.
        -- If all vertices are "comfortably" outside, we might consider it FULL_OUTSIDE.
        -- For this version, if not all 3 are IN, and not all 3 are OUT with center also out, assume PARTIAL.
        -- A more aggressive FULL_OUTSIDE would require edges not to intersect.
        -- Let's refine this: if all vertices are outside, it's only FULL_OUTSIDE if the triangle
        -- does not "straddle" the circle (e.g. circle center is far from triangle edges).
        -- This is complex. A common HTM approach: if not FULL_INSIDE, assume PARTIAL unless easily proven FULL_OUTSIDE.
        -- If v_in_count = 0 (all outside), it's likely FULL_OUTSIDE or PARTIAL.
        -- If v_in_count > 0 and v_in_count < 3, it's definitely PARTIAL.
        IF v_in_count = 0 THEN
            -- All vertices are outside. This is the trickiest case without edge checks.
            -- If circle is very small and inside triangle, HTM_GEOMETRY_UTILS.is_inside_triangle handled it.
            -- If triangle is very small and completely outside circle, this is FULL_OUTSIDE.
            -- We will assume PARTIAL and let recursion handle it, unless we can prove FULL_OUTSIDE easily.
            -- For now, if v_in_count = 0 and center is not inside, consider it PARTIAL to be safe and rely on recursion.
            -- A truly robust FULL_OUTSIDE needs more checks (e.g. separating axis theorem on sphere).
            RETURN c_status_partial_intersect; -- Safer default for v_in_count = 0 if not easily FULL_OUTSIDE
        END IF;
    END IF;
    
    RETURN c_status_partial_intersect; -- Default if not clearly fully inside or fully outside
  END check_triangle_circle_intersect_status;

  FUNCTION check_triangle_hull_intersect_status(
    tv0 HTM_VECTOR, tv1 HTM_VECTOR, tv2 HTM_VECTOR, -- Triangle vertices
    params type_hull_params
  ) RETURN INTEGER IS
    v_in_constraint_count INTEGER;
    all_vertices_outside_one_constraint BOOLEAN := FALSE;
    is_fully_inside_all_constraints BOOLEAN := TRUE;
  BEGIN
    IF params.constraint_planes IS NULL OR params.constraint_planes.COUNT = 0 THEN
      RETURN c_status_partial_intersect; -- No constraints, effectively intersects everything (or handle as error)
    END IF;

    -- Check if triangle is FULL_OUTSIDE any single constraint plane
    FOR i IN 1 .. params.constraint_planes.COUNT LOOP
      DECLARE
        n_plane HTM_VECTOR := params.constraint_planes(i);
      BEGIN
        IF n_plane.dot_product(tv0) < -c_epsilon AND
           n_plane.dot_product(tv1) < -c_epsilon AND
           n_plane.dot_product(tv2) < -c_epsilon THEN
          all_vertices_outside_one_constraint := TRUE;
          EXIT; -- Exit this loop, triangle is fully outside this plane
        END IF;
      END;
    END LOOP;

    IF all_vertices_outside_one_constraint THEN
      RETURN c_status_full_outside;
    END IF;

    -- Check if triangle is FULL_INSIDE all constraint planes
    FOR i IN 1 .. params.constraint_planes.COUNT LOOP
      DECLARE
        n_plane HTM_VECTOR := params.constraint_planes(i);
      BEGIN
        -- If any vertex is outside this constraint, then it's not fully inside all constraints
        IF n_plane.dot_product(tv0) < -c_epsilon OR
           n_plane.dot_product(tv1) < -c_epsilon OR
           n_plane.dot_product(tv2) < -c_epsilon THEN
          is_fully_inside_all_constraints := FALSE;
          EXIT; -- Exit this loop
        END IF;
      END;
    END LOOP;

    IF is_fully_inside_all_constraints THEN
      RETURN c_status_full_inside;
    END IF;

    -- Otherwise, it's partially intersecting
    RETURN c_status_partial_intersect;
  END check_triangle_hull_intersect_status;

  -----------------------------------------------------------------------------
  -- Recursive Intersection Logic
  -----------------------------------------------------------------------------
  PROCEDURE intersect_node_recursive(
    node_id NUMBER,
    p_query_level NUMBER,
    p_circle_params type_circle_params,
    p_hull_params type_hull_params,
    p_is_circle_query BOOLEAN,
    current_results IN OUT NOCOPY HTM_ID_RANGE_LIST
  ) IS
    v0 HTM_VECTOR;
    v1 HTM_VECTOR;
    v2 HTM_VECTOR;
    node_info HTM_NODE;
    node_status INTEGER;
    levels_to_descend INTEGER;
    range_low_id NUMBER;
    range_high_id NUMBER;
  BEGIN
    -- Get node's actual level first (might be dynamic)
    -- Use get_node_info for level, then get_node_vertices
    -- This avoids calling get_node_vertices for nodes that might be pruned early by level checks
    node_info := HTM_INDEX_CORE.get_node_info(node_id);

    IF node_info.level_num > p_query_level THEN
      RETURN; -- Node is finer than query level, stop.
    END IF;

    HTM_INDEX_CORE.get_node_vertices(node_id, v0, v1, v2);

    IF p_is_circle_query THEN
      node_status := check_triangle_circle_intersect_status(v0, v1, v2, p_circle_params);
    ELSE
      node_status := check_triangle_hull_intersect_status(v0, v1, v2, p_hull_params);
    END IF;

    CASE node_status
      WHEN c_status_full_outside THEN
        RETURN; -- Do nothing

      WHEN c_status_full_inside THEN
        IF node_info.level_num = p_query_level THEN
          HTM_RANGE_UTILS.add_range(current_results, node_id, node_id);
        ELSE -- node_info.level_num < p_query_level
          levels_to_descend := p_query_level - node_info.level_num;
          range_low_id := node_id * POWER(4, levels_to_descend);
          range_high_id := (node_id + 1) * POWER(4, levels_to_descend) - 1;
          HTM_RANGE_UTILS.add_range(current_results, range_low_id, range_high_id);
        END IF;

      WHEN c_status_partial_intersect THEN
        IF node_info.level_num = p_query_level THEN
          HTM_RANGE_UTILS.add_range(current_results, node_id, node_id);
        ELSIF node_info.level_num < p_query_level THEN
          -- Children IDs need to be fetched or calculated correctly
          -- If node is pre-built and not leaf, children_ids are available
          IF node_info.children_ids IS NOT NULL AND node_info.children_ids.COUNT = 4 THEN
             FOR i IN 1 .. node_info.children_ids.COUNT LOOP
                intersect_node_recursive(node_info.children_ids(i), p_query_level, p_circle_params, p_hull_params, p_is_circle_query, current_results);
             END LOOP;
          ELSIF node_info.is_leaf = 0 THEN -- Pre-built but children not explicitly stored in this HTM_NODE record (should be)
             -- Fallback to calculate children if not available in node_info, but they should be if not leaf
             FOR child_idx IN 0 .. 3 LOOP
                intersect_node_recursive((node_id * 4) + child_idx, p_query_level, p_circle_params, p_hull_params, p_is_circle_query, current_results);
             END LOOP;
          ELSE -- Node is a leaf at a level coarser than query_level, or children not available from get_node_info for dynamic nodes
               -- This case implies children should be calculated if node_info.level_num < p_query_level
             FOR child_idx IN 0 .. 3 LOOP
                intersect_node_recursive((node_id * 4) + child_idx, p_query_level, p_circle_params, p_hull_params, p_is_circle_query, current_results);
             END LOOP;
          END IF;
        END IF; -- If node_info.level_num > p_query_level, already handled at start
    END CASE;

  EXCEPTION
    WHEN OTHERS THEN
      -- Log error or raise, e.g., for invalid node_id from get_node_info if it doesn't exist
      DBMS_OUTPUT.PUT_LINE('Error in intersect_node_recursive for node ' || node_id || ': ' || SQLERRM);
      RAISE;
  END intersect_node_recursive;

  -----------------------------------------------------------------------------
  -- Public Functions
  -----------------------------------------------------------------------------
  FUNCTION circle_region_intersect(
    center_ra NUMBER,
    center_dec NUMBER,
    radius_degrees NUMBER,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST IS
    center_v HTM_VECTOR;
  BEGIN
    IF center_ra IS NULL OR center_dec IS NULL OR radius_degrees IS NULL OR query_level IS NULL THEN
        RAISE_APPLICATION_ERROR(-20200, 'Input parameters cannot be null for circle_region_intersect.');
    END IF;
    IF radius_degrees < 0 THEN
        RAISE_APPLICATION_ERROR(-20201, 'Radius cannot be negative.');
    END IF;
    IF query_level < 0 OR query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20202, 'Query level is out of range.');
    END IF;

    center_v := HTM_VECTOR(center_ra, center_dec); -- Constructor converts to Cartesian and normalizes
    RETURN circle_region_intersect_cartesian(center_v, radius_degrees, query_level);
  END circle_region_intersect;

  FUNCTION circle_region_intersect_cartesian(
    center_vec HTM_VECTOR,
    radius_degrees NUMBER,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST IS
    results HTM_ID_RANGE_LIST;
    params type_circle_params;
    root_nodes HTM_NUMBER_LIST := HTM_NUMBER_LIST(8,9,10,11,12,13,14,15); -- S0-N3
    temp_center_vec HTM_VECTOR := center_vec;
  BEGIN
    IF temp_center_vec IS NULL OR radius_degrees IS NULL OR query_level IS NULL THEN
        RAISE_APPLICATION_ERROR(-20210, 'Input parameters cannot be null for circle_region_intersect_cartesian.');
    END IF;
    IF radius_degrees < 0 THEN
        RAISE_APPLICATION_ERROR(-20211, 'Radius cannot be negative.');
    END IF;
    IF query_level < 0 OR query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20212, 'Query level is out of range.');
    END IF;

    temp_center_vec.normalize(); -- Ensure center_vec is normalized
    params.center_vec := temp_center_vec;
    params.cos_radius := COS(radius_degrees * HTM_GEOMETRY_UTILS.c_pi / 180.0);
    
    results := HTM_RANGE_UTILS.create_empty_range_list();

    FOR i IN 1 .. root_nodes.COUNT LOOP
      intersect_node_recursive(root_nodes(i), query_level, params, NULL, TRUE, results);
    END LOOP;

    HTM_RANGE_UTILS.merge_ranges(results); -- Final merge
    RETURN results;
  END circle_region_intersect_cartesian;

  FUNCTION convex_hull_intersect(
    vertices_ra_dec HTM_VERTEX_LIST,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST IS
    vertices_cart HTM_VERTEX_LIST := HTM_VERTEX_LIST();
  BEGIN
    IF vertices_ra_dec IS NULL OR vertices_ra_dec.COUNT < 3 THEN
      RAISE_APPLICATION_ERROR(-20220, 'Convex hull requires at least 3 RA/Dec vertices.');
    END IF;
    IF query_level < 0 OR query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20221, 'Query level is out of range.');
    END IF;

    vertices_cart.EXTEND(vertices_ra_dec.COUNT);
    FOR i IN 1 .. vertices_ra_dec.COUNT LOOP
      IF vertices_ra_dec(i).x IS NULL OR vertices_ra_dec(i).y IS NULL THEN
         RAISE_APPLICATION_ERROR(-20222, 'RA/Dec vertex components cannot be null.');
      END IF;
      -- Assuming x=RA, y=DEC in input HTM_VECTOR for RA/DEC list
      vertices_cart(i) := HTM_VECTOR(vertices_ra_dec(i).x, vertices_ra_dec(i).y);
    END LOOP;
    RETURN convex_hull_intersect_cartesian(vertices_cart, query_level);
  END convex_hull_intersect;

  FUNCTION convex_hull_intersect_cartesian(
    vertices_cartesian HTM_VERTEX_LIST,
    query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST IS
    results HTM_ID_RANGE_LIST;
    params type_hull_params;
    root_nodes HTM_NUMBER_LIST := HTM_NUMBER_LIST(8,9,10,11,12,13,14,15);
    num_hull_vertices NUMBER;
    v_i HTM_VECTOR;
    v_i_plus_1 HTM_VECTOR;
    plane_normal HTM_VECTOR;
  BEGIN
    IF vertices_cartesian IS NULL OR vertices_cartesian.COUNT < 3 THEN
      RAISE_APPLICATION_ERROR(-20230, 'Convex hull requires at least 3 Cartesian vertices.');
    END IF;
     IF query_level < 0 OR query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20231, 'Query level is out of range.');
    END IF;

    params.constraint_planes := HTM_VERTEX_LIST();
    num_hull_vertices := vertices_cartesian.COUNT;

    FOR i IN 1 .. num_hull_vertices LOOP
      v_i := vertices_cartesian(i);
      v_i.normalize(); -- Ensure normalized
      
      IF i = num_hull_vertices THEN
        v_i_plus_1 := vertices_cartesian(1);
      ELSE
        v_i_plus_1 := vertices_cartesian(i+1);
      END IF;
      v_i_plus_1.normalize(); -- Ensure normalized

      -- Constraint plane normal: (v_i x v_i_plus_1).normalize()
      -- Assumes vertices are ordered counter-clockwise on the sphere
      plane_normal := v_i.cross_product(v_i_plus_1);
      plane_normal.normalize();
      params.constraint_planes.EXTEND;
      params.constraint_planes(params.constraint_planes.LAST) := plane_normal;
    END LOOP;
    
    results := HTM_RANGE_UTILS.create_empty_range_list();

    FOR i IN 1 .. root_nodes.COUNT LOOP
      intersect_node_recursive(root_nodes(i), query_level, NULL, params, FALSE, results);
    END LOOP;

    HTM_RANGE_UTILS.merge_ranges(results); -- Final merge
    RETURN results;
  END convex_hull_intersect_cartesian;

END HTM_QUERY_INTERFACE;
/
SHOW ERRORS PACKAGE BODY HTM_QUERY_INTERFACE;

-- From htm_sql_api_body.sql
CREATE OR REPLACE PACKAGE BODY HTM_SQL_API AS

  -- Initialization Procedure
  PROCEDURE initialize_htm_system(
    p_build_level NUMBER,
    p_query_level NUMBER
  ) IS
  BEGIN
    IF p_build_level IS NULL OR p_query_level IS NULL THEN
      RAISE_APPLICATION_ERROR(-20300, 'Build level and query level cannot be null.');
    END IF;
    IF p_build_level < 0 OR p_query_level < 0 THEN
      RAISE_APPLICATION_ERROR(-20301, 'Build level and query level must be non-negative.');
    END IF;
    -- Further validation might be needed if HTM_INDEX_CORE has stricter limits (e.g. max query_level)
    -- For now, assume HTM_INDEX_CORE handles its own internal validation of levels.
    HTM_INDEX_CORE.initialize_htm(p_build_level, p_query_level);
  END initialize_htm_system;

  -- Lookup Functions
  FUNCTION lookup_htm_id(
    p_ra NUMBER,
    p_dec NUMBER,
    p_target_level NUMBER
  ) RETURN NUMBER IS
    vec_p HTM_VECTOR;
  BEGIN
    IF p_ra IS NULL OR p_dec IS NULL OR p_target_level IS NULL THEN
      RAISE_APPLICATION_ERROR(-20310, 'RA, Dec, and target level cannot be null.');
    END IF;
    IF p_target_level < 0 OR p_target_level > HTM_INDEX_CORE.g_max_query_level THEN
        RAISE_APPLICATION_ERROR(-20311, 'Target level is out of range. Max query level is ' || HTM_INDEX_CORE.g_max_query_level);
    END IF;

    vec_p := HTM_VECTOR(p_ra, p_dec); -- Constructor handles conversion to Cartesian
    RETURN HTM_INDEX_CORE.id_by_point(vec_p, p_target_level);
  EXCEPTION
    WHEN OTHERS THEN
      -- Could log SQLERRM here
      RAISE; -- Re-raise the exception
  END lookup_htm_id;

  FUNCTION get_htm_point_radec(
    p_htm_id NUMBER
  ) RETURN VARCHAR2 IS
    cart_vec HTM_VECTOR;
    radec_vec HTM_VECTOR;
  BEGIN
    IF p_htm_id IS NULL THEN
      RAISE_APPLICATION_ERROR(-20320, 'HTM ID cannot be null.');
    END IF;

    cart_vec := HTM_INDEX_CORE.point_by_id(p_htm_id);
    IF cart_vec IS NULL THEN -- Should not happen if point_by_id is robust
        RAISE_APPLICATION_ERROR(-20321, 'Failed to get Cartesian point for HTM ID: ' || p_htm_id);
    END IF;
    
    radec_vec := HTM_GEOMETRY_UTILS.cartesian_to_ra_dec(cart_vec);
    IF radec_vec IS NULL OR radec_vec.x IS NULL OR radec_vec.y IS NULL THEN
        RAISE_APPLICATION_ERROR(-20322, 'Failed to convert Cartesian point to RA/Dec for HTM ID: ' || p_htm_id);
    END IF;

    RETURN TO_CHAR(radec_vec.x) || ',' || TO_CHAR(radec_vec.y);
  EXCEPTION
    WHEN OTHERS THEN
      RAISE;
  END get_htm_point_radec;

  FUNCTION get_htm_point_cartesian(
    p_htm_id NUMBER
  ) RETURN HTM_VECTOR IS
  BEGIN
    IF p_htm_id IS NULL THEN
      RAISE_APPLICATION_ERROR(-20330, 'HTM ID cannot be null.');
    END IF;
    RETURN HTM_INDEX_CORE.point_by_id(p_htm_id);
  EXCEPTION
    WHEN OTHERS THEN
      RAISE;
  END get_htm_point_cartesian;

  -- Intersection Query Functions (Table Functions)
  FUNCTION htm_circle_intersect(
    p_ra NUMBER,
    p_dec NUMBER,
    p_radius_degrees NUMBER,
    p_query_level NUMBER
  ) RETURN HTM_ID_RANGE_LIST PIPELINED IS
    result_ranges HTM_ID_RANGE_LIST;
  BEGIN
    -- Validation is handled by HTM_QUERY_INTERFACE.circle_region_intersect
    -- but can add specific checks here if desired (e.g. for nulls early)
    IF p_ra IS NULL OR p_dec IS NULL OR p_radius_degrees IS NULL OR p_query_level IS NULL THEN
      RAISE_APPLICATION_ERROR(-20340, 'Circle parameters (RA, Dec, Radius, Level) cannot be null.');
    END IF;
     IF p_query_level < 0 OR p_query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20341, 'Query level is out of range.');
    END IF;


    result_ranges := HTM_QUERY_INTERFACE.circle_region_intersect(p_ra, p_dec, p_radius_degrees, p_query_level);

    IF result_ranges IS NOT NULL THEN
      FOR i IN 1 .. result_ranges.COUNT LOOP
        PIPE ROW (result_ranges(i));
      END LOOP;
    END IF;
    RETURN;
  EXCEPTION
    WHEN OTHERS THEN
      -- DBMS_OUTPUT.PUT_LINE('Error in htm_circle_intersect: ' || SQLERRM);
      RAISE;
  END htm_circle_intersect;

  FUNCTION htm_polygon_intersect(
    p_vertices_ra_dec_string VARCHAR2,
    p_query_level NUMBER,
    p_delimiter CHAR DEFAULT ';'
  ) RETURN HTM_ID_RANGE_LIST PIPELINED IS
    vertex_list HTM_VERTEX_LIST := HTM_VERTEX_LIST();
    ra_dec_pairs DBMS_SQL.VARCHAR2_TABLE; -- Using a PL/SQL table for split results
    current_pair_str VARCHAR2(100);
    ra_str VARCHAR2(50);
    dec_str VARCHAR2(50);
    ra_val NUMBER;
    dec_val NUMBER;
    pos_delimiter NUMBER;
    pos_comma NUMBER;
    
    temp_string VARCHAR2(32767) := p_vertices_ra_dec_string; -- Max length for varchar2 in PLSQL
    result_ranges HTM_ID_RANGE_LIST;

  BEGIN
    IF p_vertices_ra_dec_string IS NULL OR p_query_level IS NULL THEN
      RAISE_APPLICATION_ERROR(-20350, 'Polygon vertices string and query level cannot be null.');
    END IF;
    IF p_query_level < 0 OR p_query_level > HTM_INDEX_CORE.g_max_query_level THEN
       RAISE_APPLICATION_ERROR(-20351, 'Query level is out of range.');
    END IF;
    IF LENGTH(p_vertices_ra_dec_string) = 0 THEN
        RAISE_APPLICATION_ERROR(-20352, 'Polygon vertices string cannot be empty.');
    END IF;

    -- Basic split logic, can be enhanced with REGEXP_SUBSTR for more complex cases or different Oracle versions.
    LOOP
      pos_delimiter := INSTR(temp_string, p_delimiter);
      IF pos_delimiter > 0 THEN
        current_pair_str := TRIM(SUBSTR(temp_string, 1, pos_delimiter - 1));
        temp_string := TRIM(SUBSTR(temp_string, pos_delimiter + 1));
      ELSE
        current_pair_str := TRIM(temp_string);
        temp_string := NULL; -- No more delimiters
      END IF;
      
      IF LENGTH(current_pair_str) > 0 THEN
        pos_comma := INSTR(current_pair_str, ',');
        IF pos_comma IS NULL OR pos_comma = 0 OR pos_comma = LENGTH(current_pair_str) THEN
          RAISE_APPLICATION_ERROR(-20353, 'Invalid RA,Dec format in polygon string: "' || current_pair_str || '". Expected "RA,DEC".');
        END IF;
        ra_str := TRIM(SUBSTR(current_pair_str, 1, pos_comma - 1));
        dec_str := TRIM(SUBSTR(current_pair_str, pos_comma + 1));

        BEGIN
          ra_val := TO_NUMBER(ra_str);
          dec_val := TO_NUMBER(dec_str);
        EXCEPTION
          WHEN VALUE_ERROR THEN
            RAISE_APPLICATION_ERROR(-20354, 'Invalid number format for RA or Dec in polygon string: "' || current_pair_str || '".');
        END;
        
        -- Store RA as x, Dec as y for HTM_QUERY_INTERFACE.convex_hull_intersect
        vertex_list.EXTEND;
        vertex_list(vertex_list.LAST) := HTM_VECTOR(ra_val, dec_val, 0); -- z is not used by convex_hull_intersect for RA/Dec inputs
      END IF;

      EXIT WHEN temp_string IS NULL OR LENGTH(temp_string) = 0;
    END LOOP;
    
    IF vertex_list.COUNT < 3 THEN
      RAISE_APPLICATION_ERROR(-20355, 'Polygon requires at least 3 vertices. Parsed ' || vertex_list.COUNT || ' vertices.');
    END IF;

    result_ranges := HTM_QUERY_INTERFACE.convex_hull_intersect(vertex_list, p_query_level);

    IF result_ranges IS NOT NULL THEN
      FOR i IN 1 .. result_ranges.COUNT LOOP
        PIPE ROW (result_ranges(i));
      END LOOP;
    END IF;
    RETURN;
  EXCEPTION
    WHEN OTHERS THEN
      -- DBMS_OUTPUT.PUT_LINE('Error in htm_polygon_intersect: ' || SQLERRM);
      RAISE;
  END htm_polygon_intersect;

END HTM_SQL_API;
/
SHOW ERRORS PACKAGE BODY HTM_SQL_API;

PROMPT HTM Compilation Script Complete.
